// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENpSdm2J2Foo2ZzxyId4_pGvK4dUE5xI',
    appId: '1:42913072703:web:a8f98eadae1b2991739a8a',
    messagingSenderId: '42913072703',
    projectId: 'lostkuet',
    authDomain: 'lostkuet.firebaseapp.com',
    storageBucket: 'lostkuet.firebasestorage.app',
    measurementId: 'G-2FN8HWS78F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgpWY5BrZvLGiikteqfPO4K-wNrEVpdwg',
    appId: '1:42913072703:android:ae03b48d29a7773d739a8a',
    messagingSenderId: '42913072703',
    projectId: 'lostkuet',
    storageBucket: 'lostkuet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3RS3mPWHhBrgI8qz63ai8yBF1B8HXl8',
    appId: '1:42913072703:ios:5e183e2d928e8dc7739a8a',
    messagingSenderId: '42913072703',
    projectId: 'lostkuet',
    storageBucket: 'lostkuet.firebasestorage.app',
    iosBundleId: 'com.example.lostatkuet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT3RS3mPWHhBrgI8qz63ai8yBF1B8HXl8',
    appId: '1:42913072703:ios:5e183e2d928e8dc7739a8a',
    messagingSenderId: '42913072703',
    projectId: 'lostkuet',
    storageBucket: 'lostkuet.firebasestorage.app',
    iosBundleId: 'com.example.lostatkuet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDENpSdm2J2Foo2ZzxyId4_pGvK4dUE5xI',
    appId: '1:42913072703:web:c96709813e5e1b14739a8a',
    messagingSenderId: '42913072703',
    projectId: 'lostkuet',
    authDomain: 'lostkuet.firebaseapp.com',
    storageBucket: 'lostkuet.firebasestorage.app',
    measurementId: 'G-NJ5L5J826L',
  );
}
